{
 "title": "Basic Dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Xavier NX Jtop", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "xavier_nx_cpu_util_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "xavier_nx_cpu_freq_khz", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "xavier_nx_gpu_util_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature (C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "xavier_nx_thermal_celsius", "legendFormat": "__auto" }
   ]
  },
  { "title": "Xavier NX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Xavier NX Power (W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 18 },
   "targets": [
    { "expr": "xavier_nx_power_watts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Xavier NX Voltage (V)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "xavier_nx_voltage_volts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Xavier NX Current (A)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "xavier_nx_current_amps", "legendFormat": "__auto" }
   ]
  },
  { "title": "AGX Xavier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "AGX Xavier Power (W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 35 },
   "targets": [
    { "expr": "agx_xavier_power_watts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AGX Xavier Voltage (V)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    { "expr": "agx_xavier_voltage_volts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AGX Xavier Current (A)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    { "expr": "agx_xavier_current_amps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AGX Orin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true
  },
  {
   "title": "AGX Orin Power (W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 52 },
   "targets": [
    { "expr": "agx_orin_power_watts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AGX Orin Voltage (V)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    { "expr": "agx_orin_voltage_volts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AGX Orin Current (A)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    { "expr": "agx_orin_current_amps", "legendFormat": "__auto" }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "PyJoules signals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "targets": [
    { "expr": "pyjoules_multirate_energy_uj", "legendFormat": "__auto" },
    { "expr": "pyjoules_simple_energy_watts", "legendFormat": "__auto" },
    {
     "expr": "pyjoules_remote_write_energy_uj",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}